### ISSUE TITLE
Show which parts of an article are implemented

### ISSUE THREAD

**Issue by TristanAlbers** [discipl/flinteditor-mps#108]
If an line in an Article is already implemented in the selected model it should be underlined.

![image](https://user-images.githubusercontent.com/37440544/163399954-cdafe77f-f7a5-4447-bf90-f5cb1f57cdd4.png)

**Comment by blackstardlb** [comment]
Also include the specific nodes that uses the article part. This can be shown in the node inspector for example.

**Comment by blackstardlb** [comment]
Show percentage of used lines for article and version
