### ISSUE TITLE
Shared acts

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#128]
I want to be able to specify multiple actors within act frames that allow for multiple actors (e.g. processing).

**Comment by TristanAlbers** [comment]
This is current possible via the method described below. Multiple actors in a single role is not viable per the whitepaper.

[actor : text, needs to be a fact that defines a certain actor (and how to identify/authenticate an actor in a certain role). The actor refers to an agent attending to the needs of the recipient for the result of taking the defined action on the object (including providing this object) defined in this action](https://github.com/discipl/discipl-law-reg/blob/master/doc/vision.md)

![image](https://user-images.githubusercontent.com/37440544/166680267-436426d6-3c32-4e82-8d30-d9fdf103d3ee.png)
