### ISSUE TITLE
The action property on acts is not a fact reference

### ISSUE THREAD

**Issue by n9iels** [discipl/flinteditor-mps#15]
Currently the flint editor is assuming that a `action` property of an Act holds a fact reference. However this seems not the case since a lot of models (Like the [Tegemoetkoming schade COVID-19](https://github.com/discipl/regelingen-check/blob/master/compliance-by-design-demo/src/model/tegemoetkoming-schade-covid19.flint.json) do have actions with no defined fact.

**Comment by blackstardlb** [comment]
close in #23
