### ISSUE TITLE
Document what embeddr plugins are used. 

### ISSUE THREAD

**Issue by blackstardlb** [discipl/flinteditor-mps#205]

**Comment by TristanAlbers** [comment]
com.mbeddr as mbeddr:  
- mbeddr.platform
    - Reference to complete platform for build
- mbeddr.mpsutil.json  
    - Used to create JSON generators
- mbeddr.mpsutil.projectview 
    - Used to create the custom FlintView
- mbeddr.mpsutil.datepicker
    - Used to import a datepicker
- mbeddr.mpsutil.editor.querylist
    - Used to create querylists inside the editor. Querylist can query and display a list of nodes
- mbeddr.mpsutil.hyperlink
    - Used to create hyperlinks to other nodes

de.itemis.mps as itemis:  
- itemis.extensions.build
    - Reference to complete platform for build
- itemis.editor.diagram
    - Used to create a diagram
- itemis.selection.intentions 
    - Used to create intentions spanning multiple nodes

de.slisson.mps as slisson:  
- slisson.richtext  
    - Used for better handling of text and words inside the editor
- slisson.editor.multiline
    - Used to create multilines inside the editor
- slisson.hacks.editor
    - Provides extra utility for the editor. Also used in **slisson.richtext**. Used to acces saved caret position in custom Flint text.

**Comment by cblazo** [comment]
@blackstardlb Can you check this list and see there are missing dependencies?
