### ISSUE TITLE
Error and warning checklist

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#207]
Please provide a list of all the rules against which the Flint model (and LawSource?) are checked, what the error message is, and where the rules are implemented. 

Here are some examples of how I see the difference:

**Errors**
- Actor field may not be empty
- Recipient field contains a complex Fact
- Postconditional fact is not CREATABLE

**Warnings - Syntax / code style**
- Fact name contains boolean logic ('and' / 'or'), consider splitting the fact into atomic facts
- Another Duty with that name exists
- This Fact is used as both precondition and postcondition of the same Act
-

**Comment by TristanAlbers** [comment]
> Might be addressed in #195 though, @TristanAlbers ?
@cblazo 
Yes, Typesystem & Constraints should cover this topic
