### ISSUE TITLE
Document dependencies / external packages and their usage

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#208]
What is the usage of the following external libraries etc? 
(references found in [build-gradle](https://github.com/discipl/flinteditor-mps/blob/master/build.gradle)

- Maven
- Mbeddr mbeddr_version = "2021.2.+"
- OpenJFX
- Itemis gradle plugin
- Dom4j 1.6.1
- Jaxen 1.2.0
- Github node 2.2.3
- Java
- Download jbr
- OSS index audit 0.4.11
- javafx_version = "14"
- mps_version = "2021.2.5"
- node_version = "13.6.0"
- npm_version = "6.13.4"
- koin_version = "3.2.0-beta-1"
- ktor_version = "2.0.2"
- gson_version = "2.8.6"
- jbr_version = "11_0_6-b520.66"
- osx_jdk_version = "11.0.11-9"
- FlintParser – logic for importing models, and flint filler
- FlintFiller 0.0.5
- FlintSources – logic for importing and parsing sources
- Googlecode json-simple 1.1.1
- Commons IO 2.11.0
- Apache ant Junit 1.10.12

**Comment by TristanAlbers** [comment]
List of dependencies. Removed some ducplicates, added some more dependencies
@blackstardlb **Please provide edits/feedback if incomplete or lacking**

- Maven
    - Software project manageement tool, used to manage a projects build.
- Mbeddr mbeddr_version = "2021.2.+"
    - Contains languages which enrich mps functionalities, usage inside Flint
- Itemis gradle plugin
    - Contains languages which enrich mps functionalities, usage inside Flint
- Dom4j 1.6.1
    - Library for working with XML, XPath, DOM
- Jaxen 1.2.0
    - Library for working with XML, XPath, DOM (Compatible with Dom4j)
- Github node 2.2.3
    - Enables user to use a lot of Node.js based technologies as part of the build without having Node.js installed locally.
- Java
    - Usage of programming language inside MPS (kotlin is also fully interoperate with Java)
- Kotlin
    - Usage of programming language inside both FlintParser and FlintSources
- OSS index audit 0.4.11
    - Usage in auditing dependencies, keeping track of vulnerabilities
- javafx_version = "14"
    - Library containing UI elements. Used inside FlintRunner project to create the UI inside MPS.
- mps_version = "2021.2.5"
    - Usage of programming language (Latest possible version bc of compatibility with mbeddr)
- node_version = "13.6.0"
    - Node.js version, Used to create/run FlintRunner
- npm_version = "6.13.4"
    - Package manager for Node.js, Used to create/run FlintRunner
- koin_version = "3.2.0-beta-1"
    - Usage in code injection for kotlin
- ktor_version = "2.0.2"
    - Usage in making asynchronous calls to a server
- gson_version = "2.8.6"
    - Usage in parsing json to java classes, finds it usage in the kotlin projects
- jbr_version = "11_0_6-b520.66"
    - Usage in bundling FlintEditor
- osx_jdk_version = "11.0.11-9"
    - Usage in bundling java development kit in FlintEditor for MacOs (osx)
- FlintParser   
    - logic for importing models, and flint filler
- FlintFiller 0.0.5
    - logic for parsing juriconnect to complete FlintModel
- FlintSources 
    - logic for importing and parsing sources
- Googlecode json-simple 1.1.1
    - Library to work with JSON files, finds it usage inside MPS project
- jsoup
    - Java library for working with HTML
- ch.qos.logback
    - Logging library
- Commons IO 2.11.0
    - Secondary dependency from mbeddr, contains libraries to assist in IO (Input/Output) functionality
- Apache ant Junit 1.10.12
    - Testing framework
- Hamcrest
    - Testing framework
- Jena
    - Library for calling SPARQL queries

**Comment by cblazo** [comment]
@blackstardlb Can you check if there is something missing or should be changed?

**Comment by blackstardlb** [comment]
- Maven (Software project manageement tool, used to manage a projects build.)
We don't use maven for this we use gradle. Which uses maven repositories. 

- Itemis gradle plugin
this is used to build MPS languages and run MPS tests

- node_version = "13.6.0" (Node.js version, Used to create/run FlintRunner)
npm_version = "6.13.4" (Package manager for Node.js, Used to create/run FlintRunner)
node and npm are used to download the latest version of ComplianceByDesign to include for the FlintRunner.

- koin_version = "3.2.0-beta-1" (Usage in code injection for kotlin)
Dependency injection

we also have  'com.cosminpolifronie.gradle.plantuml:1.6.0' plugin now to render plantuml diagrams
