### ISSUE TITLE
Check functional requirements [@Daron]

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#217]
These general functions allow users to explicate interpretations in a model:

1.  **Importing** of Norm Sources, Flint models and UI language into the IDE environment, from different sources (local file, web service)
2. **Tagging** of Norm Sources, to create a link between Norm Source and Flint frame fields
3. **Editing** and creating the Norm Sources, Flint models and UI language
4. **Annotating** and **versioning** of Norm Sources and Flint frames
5. **Verifying** and **validating** of the Flint model and its mapping to the Norm Source
6. **Exporting** of Norm Source, Flint model and UI language to standardized formats

The full list is:
 	|Function|Requirement|Description|
|:----|:----|:----|
|Importing|Import FLINT model from JSON|Able to import a Flint model and its links from JSON to a decomposed NormSource|
| |Import FLINT model from FlintFiller|Able to import a Flint model by passing a juriconnect to the FlintFiller|
| |Import NormSource from parser|Able to import a decomposed NormSource in a standardized format via parsers|
| |Import NormSource from JSON|Able to import a decomposed NormSource in a standardized format from a JSON file|
| |Import editor language|Able to import an editor language in a standardized format|
|Tagging|Tagging as Frame|Able to create a Flint frame based on a text selection in a NormSource|
| |Tagging in Flint frames|Able to tag parts of a decomposed NormSource reference inside a flint frame to properties of that fint frame|
| |~~Suggest frames~~|~~Able to consult the Flint Filler to suggest a mapping~~|
|Creating|Create project|Able to create an empty project and set the meta-information (Name, description)|
| |~~Create Norm Source~~|~~Able to create a Norm Source part~~|
| |Create FLINT model|Creating an empty (or template) Flint model|
| |Create Flint frame|Able to create an empty Flint (Act, Fact, Duty) frame|
|Editing|Editing FLINT model|Add or change fields of a Flint frame|
| |Create preconditions|Able to create preconditions and functions in Flint Frames using boolean algebra and references to other Flint frames|
| |Archiving Flint frame|Able to archive a Flint frame so that it is inactive, hidden and unlinked from other Flint frames|Editing decomposed Norm Source|Change the text of a decomposed Norm Source part|
| |Create editor language|Able to create translations of the editor labels and use them|
| |Create translations|Able to create translations on names, tags, and sources of a decomposed Norm Source part|
|Annotating|Explanation|Able to add an ‘explanation’ field with a string input to Flint frames (Fact, Act, Duty) and NormSource objectsVersioning|Flint model versioning|Able to create new versions of a Flint model (Git-like)|
| |Source validity|Able to specify for a Norm Source between which dates it is valid.|
|Verification|Error checking|Check whether the Flint model adheres to the rules in Appendix: Error and syntax checking rules|
| |Syntax checking|Check whether the Flint model adheres to the rules in Appendix: Error and syntax checking rules|
| |Diagnostics|The IDE reports many messages to the user: info, warnings and errors|
|Validation|Mapping validation|Able to see and trace which parts of a Norm Source are mapped to a specific Flint model|
| |Tracking validation status|Able to mark validation progress of a Flint frame as verified, validated or published|
| |Mapping coverage|Able to see the ratio of tagged/untagged parts of the decomposed Norm Source to a specific Flint model|
| |*FlintRunner*|*(Deprecated) Able to write a simple test case and test the logics of the Flint model via a simple UI*|
|Exporting|Export FLINT model|Able to export the Flint model and its links to a decomposed Norm Source to a standardized file format.|
| |Export NormSource model|Able to export the NormSource model to a standardized file format|
| |Export editor language|Able to export the editor language to a standardized file format.|

**Comment by blackstardlb** [comment]
We also have Search functionality to search in a FlintModel / NormSource Version.
