### ISSUE TITLE
Check non-functional requirements

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#218]
In hindsight, which non-functional requirements were there for the MPS IDE?

What I've found so far:
- Use the Flint DSL specification
- The IDE is open source, under an Apache 2.0 licence
- Documentation: User & dev guides
- Source documents come from wetten.nl, using [Juriconnect](https://www.koopoverheid.nl/standaarden/juriconnect) standard
- Parsing via Triply and NSX servers

Do you have any additions/changes to this list?

**Comment by TristanAlbers** [comment]
Looks good to me 👍
