### ISSUE TITLE
Ambiguity in diagram text

### ISSUE THREAD

**Issue by cblazo** [discipl/flinteditor-mps#220]
Is the 'Editor' in these diagrams the 'LawSource Editor' as in other diagrams? Is there a significant difference between the Editor and LawSource
https://github.com/discipl/flinteditor-mps/blob/master/docs/diagrams/sequence/renders/version-importing.png
https://github.com/discipl/flinteditor-mps/blob/master/docs/diagrams/sequence/renders/source-importing.png

Similarly there is a 'Source Service' and a 'SourceText Service'. How are they different, and how do they relate to each other?
https://raw.githubusercontent.com/discipl/flinteditor-mps/master/docs/diagrams/sequence/renders/source-text-importing.png

Here, there's a 'SourceTextService' and a 'sourceTextService', which is confusing.
https://raw.githubusercontent.com/discipl/flinteditor-mps/master/docs/diagrams/sequence/renders/editor-version-content-import.png

**Comment by TristanAlbers** [comment]
The first two diagrams are high level diagrams, this might explain the discrepancies. The version-importing is called from the `LawSourceEditor` while the second one is called from the `VersionEditor`

**Comment by TristanAlbers** [comment]
@cblazo After conferring with Daron i found the following:

- `SourceTextService` gathers the actual text parts from the source
- `SourceService` gathers the 'header info' of the source. Namely the juriconnect and the name
- `SourceService` and `VersionService` are zoomed in diagrams of the headers displayed in [editor-source-and-version-import](https://github.com/discipl/flinteditor-mps/blob/master/docs/diagrams/sequence/renders/editor-source-and-version-import.png) this is also where the ambiguity in the name 'Editor' comes from. These classes find their place inside the kotlin code, the 'Editor' name refers to the MPS layer from which they are called. 
- `SourceTextService` and `sourceTextService` are the same thing. This is a type for which i'll create a new pull-request
