### ISSUE TITLE
Make release (and release process)

### ISSUE THREAD

**Issue by pimotte** [discipl/flinteditor-mps#4]
For easy distribution. If we just distribute the plugin in we can use github releases, if we want to distribute the full IDE we might want to check if we don't run into some fair use limit.

**Comment by blackstardlb** [comment]
According to (here)[https://help.github.com/en/github/administering-a-repository/about-releases]: Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage. They IDE's are around 500mb each so we should be fine.
