### ISSUE TITLE
Moonshot: Provide "import from wetten.nl" using FlintFiller

### ISSUE THREAD

**Issue by pimotte** [discipl/flinteditor-mps#5]
See https://gitlab.com/calculemus-flint/flintfiller

Integrating this can be done by either embedding the FlintFiller tool or by hosting it as a service somewhere. The prior is likely the preferred way to go. 

This story would lead to a way to create a new Flint model by supplying a juriconnect pointing to an entire law. In the future, FlintFiller-technology could be used to supply on-demand autocompletion and suggestion, but this is out of scope for this issue.

**Comment by blackstardlb** [comment]
close in #24
