### ISSUE TITLE
Geldigheid van een onderdeel in een source 

### ISSUE THREAD

**Issue by TristanAlbers** [discipl/flinteditor-mps#84]
Add following fields to Line:
- datum geldig vanaf
- datum geldig tot
- datum terugwerkendekracht

Field may be empty and manually filled in for now until the backend provides this data

**Comment by blackstardlb** [comment]
TODO // Update this

**Comment by TristanAlbers** [comment]
terugwerkende kracht eerder dan geldig vanaf constraint
